apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coursera-cluster
  region: us-west-1
  version: "1.20"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: autoscaler-service
        namespace: kube-system
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribeAutoScalingInstances"
              - "autoscaling:DescribeLaunchConfigurations"
              - "autoscaling:DescribeTags"
              - "autoscaling:SetDesiredCapacity"
              - "autoscaling:TerminateInstanceInAutoScalingGroup"
              - "ec2:DescribeLaunchTemplateVersions"
            Resource: "*"

managedNodeGroups:
  - name: nodegroup-coursera
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80
    minSize: 2
    maxSize: 4
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
